---
name: Pull Request Template
about: Template para crear nuevos pull requests
title: 'Feature: Etapa 4 - Testing y Documentación'
labels: 'testing, documentation'
assignees: 'SebastianFernandezOK'
---

## Descripción
Se completó la Etapa 4 del trabajo práctico. Se agregaron tests unitarios y de integración para todos los servicios, repositorios y controladores. Además, se creó un `README.md` completo con instrucciones de instalación, uso y documentación de endpoints.

## Issue Relacionado
Closes #4

## Tipo de Cambio
- [x] Nueva característica
- [x] Mejora de documentación
- [x] Test

## Cambios Realizados
- [x] Tests de `LibroServiceImpl`, `UsuarioServiceImpl` y `PrestamoServiceImpl` usando Mockito
- [x] Tests de `LibroRepositoryImpl`, `UsuarioRepositoryImpl` y `PrestamoRepositoryImpl`
- [x] Tests de integración para todos los controladores usando `@WebMvcTest`
- [x] Archivo `README.md` con estructura detallada del proyecto
- [x] Documentación de todos los endpoints REST

## Pruebas Realizadas
- [x] `mvnw test` ejecutado exitosamente
- [x] Todos los tests pasan sin errores (19 en total)
- [x] Revisión manual de la API en Postman

## Capturas de Pantalla
_No aplica_

## Checklist
- [x] El código sigue las convenciones de estilo
- [x] Se han agregado/actualizado los tests necesarios
- [x] La documentación ha sido actualizada
- [x] Los tests pasan correctamente
- [x] El código está libre de warnings
- [x] Se han resuelto los conflictos de merge

## Notas Adicionales
Se da por finalizado el desarrollo del TP4. Todos los tests están organizados por capa y el proyecto cumple con los requisitos de arquitectura, SOLID y documentación.
