---
name: Pull Request Template
about: Template para crear nuevos pull requests
title: 'Etapa 2 - Repositories y Services'
labels: 'repository, service'
assignees: 'SebastianFernandezOK'

---

## Descripción
Este Pull Request implementa la Etapa 2 del sistema de gestión de biblioteca. Se desarrollaron las interfaces y clases concretas para los repositorios y servicios de las entidades `Libro`, `Usuario` y `Prestamo`, utilizando estructuras en memoria (`Map`) para simular la persistencia. Se aplicaron los principios SOLID (ISP y DIP) en el diseño.

## Issue Relacionado
Closes #2

## Tipo de Cambio
- [x] Nueva característica
- [ ] Corrección de bug
- [ ] Mejora de documentación
- [ ] Refactorización
- [ ] Test

## Cambios Realizados
- [x] Interfaces `LibroRepository`, `UsuarioRepository`, `PrestamoRepository`
- [x] Implementaciones en memoria para cada repositorio
- [x] Interfaces `LibroService`, `UsuarioService`, `PrestamoService`
- [x] Implementaciones de los servicios con inyección de dependencias
- [x] Separación por paquetes y anotaciones `@Repository` / `@Service`

## Pruebas Realizadas
- [x] Test manual desde `main()`: creación de objetos y operaciones básicas
- [x] Verificación de funcionamiento de `guardar`, `buscar`, `eliminar`
- [x] El proyecto compila y arranca correctamente

## Capturas de Pantalla
_No aplica para esta etapa_

## Checklist
- [x] El código sigue las convenciones de estilo
- [x] No hay errores de compilación
- [x] Los servicios funcionan como se espera
- [x] Se organizó correctamente por capas
- [x] Se respetaron los principios SOLID
- [x] El PR cierra el Issue asociado

## Notas Adicionales
Listo para revisión y merge a `main` o `develop`.
