---
name: Pull Request Template
about: Template para crear nuevos pull requests
title: 'Etapa 3 - Controladores REST'
labels: 'controller'
assignees: 'SebastianFernandezOK'

---

## Descripción
Este Pull Request implementa la Etapa 3 del sistema de gestión de biblioteca. Se desarrollaron los controladores REST para `Libro`, `Usuario` y `Prestamo`, con endpoints básicos para operaciones CRUD. Se aplicó el principio DIP inyectando los servicios por constructor.

## Issue Relacionado
Closes #3

## Tipo de Cambio
- [x] Nueva característica
- [ ] Corrección de bug
- [ ] Mejora de documentación
- [ ] Refactorización
- [ ] Test

## Cambios Realizados
- [x] Creación de `LibroController`
- [x] Creación de `UsuarioController`
- [x] Creación de `PrestamoController`
- [x] Endpoints: GET, POST, PUT, DELETE
- [x] Inyección de servicios por constructor

## Pruebas Realizadas
- [x] Test manual con Postman o curl
- [x] Validación de creación, consulta y eliminación de entidades
- [x] Inicio exitoso del servidor

## Capturas de Pantalla
_No aplica_

## Checklist
- [x] El código compila correctamente
- [x] Se aplicó DIP correctamente
- [x] Se usó la estructura de paquetes adecuada
- [x] El PR cierra el Issue asociado

## Notas Adicionales
Listo para revisión y merge a `main` o `develop`.
