---
name: Issue Template
about: Template para crear nuevos issues
title: 'Etapa 2 - Repositories y Services'
labels: 'repository, service'
assignees: 'SebastianFernandezOK'
---

## Descripción
Implementar la capa de repositorios y servicios para las entidades del sistema de gestión de biblioteca: `Libro`, `Usuario` y `Prestamo`. Se deben aplicar los principios SOLID (ISP y DIP) y trabajar con una implementación en memoria.

## Requisitos Técnicos
- [x] Crear interfaz `LibroRepository` y clase `LibroRepositoryImpl`
- [x] Crear interfaz `UsuarioRepository` y clase `UsuarioRepositoryImpl`
- [x] Crear interfaz `PrestamoRepository` y clase `PrestamoRepositoryImpl`
- [x] Crear interfaz `LibroService` y clase `LibroServiceImpl`
- [x] Crear interfaz `UsuarioService` y clase `UsuarioServiceImpl`
- [x] Crear interfaz `PrestamoService` y clase `PrestamoServiceImpl`
- [x] Usar `Map<Long, T>` para simular persistencia
- [x] Aplicar ISP y DIP en el diseño

## Criterios de Aceptación
- [x] El proyecto compila sin errores
- [x] Las implementaciones devuelven resultados esperados
- [x] Se puede guardar, buscar y eliminar libros, usuarios y préstamos
- [x] Todos los servicios están anotados con `@Service` y repositorios con `@Repository`
- [x] El código es claro, limpio y separado por paquetes

## Dependencias
- [x] Etapa 1 completada

## Complejidad
- [ ] Baja
- [x] Media
- [ ] Alta

## Labels
- [x] `repository`
- [x] `service`

## Asignación
- Milestone: Etapa 2: Repositories y Services  
- Project: Sistema de Gestión de Biblioteca  
- Estado: To Do
